Repository humanmade/altis-local-server, pull requests merged in 2019-11, with the labels that each got.

#56 Map QM paths to host file paths
  composer.json
  docker/docker-compose.yml
  inc/composer/class-command-provider.php
  inc/composer/class-command.php
  inc/composer/class-plugin.php
  inc/namespace.php
Labels: enhancement

#81 Restart cavalcade on failure
  docker/docker-compose.yml
Labels: backport v1-branch, backport v2-branch, backport v3-branch, bug

#80 Pin container versions to fixed releases
  docker/docker-compose.yml
  inc/composer/class-command.php
Labels: backport v3-branch

#85 Make sure all commands return their exit codes
  inc/composer/class-command.php
Labels: backport v3-branch
