Repository humanmade/altis-local-server, pull requests merged in 2019-12, with the labels that each got.

#90 #65 Document Windows 10 Home Edition limitation
  docs/troubleshooting.md
Labels: backport v3-branch

#89 Add shared socket volume for nginx/php socket communication
  docker/docker-compose.yml
  inc/composer/class-command.php
Labels: backport v3-branch, enhancement

#91 Change command name to `server`
  docs/README.md
  docs/cli.md
  docs/php-debugging.md
  docs/troubleshooting.md
  docs/viewing-logs.md
  inc/composer/class-command.php
Labels: backport v3-branch

#95 Add Elasticsearch & Kibana docs
  docs/assets/kibana-dev-tools.png
  docs/assets/kibana-discover.png
  docs/assets/kibana-index-patterns.png
  docs/elasticsearch.md
  docs/email.md
  docs/using-xdebug.md
Labels: backport v3-branch

#97 Use Tachyon 2.2.0
  docker/docker-compose.yml
Labels: backport v3-branch

#100 Escape working directory argument
  inc/composer/class-command.php
Labels: backport v1-branch, backport v2-branch, backport v3-branch

#104 Fix tachyon docker image
  docker/docker-compose.yml
Labels: backport v3-branch

#108 Pass ES_MEM_LIMIT env var through to docker compose process
  inc/composer/class-command.php
Labels: backport v3-branch
