Repository humanmade/altis-local-server, pull requests merged in 2020-10, with the labels that each got.

#159 Generate docker-compose.yml file in PHP
  composer.json
  docker/docker-compose.yml
  inc/composer/class-command.php
  inc/composer/class-docker-compose-generator.php
Labels: sprint 1

#226 Fix proxy restart, stop and destroy commands
  inc/composer/class-command.php
Labels: backport v4-branch, backport v5-branch

#231 [Backport v5-branch] Add Composer v2 support
  composer.json
  inc/composer/class-plugin.php
Labels: backport v3-branch, backport v4-branch
