Repository humanmade/altis-local-server, pull requests merged in 2020-06, with the labels that each got.

#169 Fix memory usage in ES
  docker/docker-compose.yml
Labels: backport v3-branch

#171 Stop containers restarting if docker daemon rebooted
  docker/docker-compose.yml
Labels: backport v3-branch, backport v4-branch

#174 Increase healtcheck timeout for ElasticSearch
  docker/docker-compose.yml
Labels: backport v4-branch
