Repository humanmade/altis-local-server, pull requests merged in 2021-12, with the labels that each got.

#391 Do not remove or stop proxy unless indicated
  docs/README.md
  docs/troubleshooting.md
  inc/composer/class-command.php
Labels: backport v6-branch, backport v7-branch, backport v8-branch, backport v9-branch

#393 [Backport v8-branch] Do not remove or stop proxy unless indicated
  docs/README.md
  docs/troubleshooting.md
  inc/composer/class-command.php
Labels: backport v6-branch, backport v7-branch

#398 Use correct placeholder in sequel template
  templates/sequel.xml
Labels: backport v9-branch
