Repository humanmade/altis-local-server, pull requests merged in 2022-01, with the labels that each got.

#404 Ensure to disable pseudo-tty when get db info
  inc/composer/class-command.php
Labels: backport v6-branch, backport v7-branch, backport v8-branch, backport v9-branch, backport v10-branch

#409 Renew SSL certificates for 2022
  docker/sni/cert/altis.pem
  docker/sni/key/altis.pem
  docker/ssl.cert
  docker/ssl.key
Labels: backport v6-branch, backport v7-branch, backport v8-branch, backport v9-branch, backport v10-branch

#416 cert-2022-line-break
  docker/ssl.cert
Labels: backport v5-branch, backport v6-branch, backport v7-branch, backport v8-branch, backport v9-branch, backport v10-branch

#423 [Backport v7-branch] Ensure to disable pseudo-tty when get db info
  inc/composer/class-command.php
Labels: backport v6-branch
