Repository humanmade/altis-local-server, pull requests merged in 2023-02, with the labels that each got.

#574 Avoid warnings for mkcert
  inc/composer/class-command.php
Labels: bug

#531 Display site URL after restarting
  inc/composer/class-command.php
Labels: story

#581 Update dependabot for v14 release
  .github/dependabot.yml
Labels: backport v14-branch
